### PR TITLE
Fix JsonStreamParser.head[J]

### PR DESCRIPTION
**Pull request by mdedetrich**
Resolves: https://github.com/mdedetrich/pekko-streams-circe/issues/15

@gchudnov I am trying to create a failing test for this usecase, specifically a lazy streamed chunked http response (in response to what you wrote in the issue) and I am not having much luck. Would it be possible to help out here, i.e. do you have some idea of the JSON content that was causing the problem or maybe it was another issue (i.e. the chunks were coming in extremely slowly???)

### CODE REVIEW

**Comment by mdedetrich** [comment]
Okay so I think I may have gotten somewhere, i.e. if I add a `.delay(10.seconds)` to the `Source` that provides the chunked data then I get empty head of list, I guess there is some timeout going on here.

Lets see if I can reproduce this in akka-streams JSON to see if behaviour is the same or different.

**Comment by mdedetrich** [comment]
So annoying news, I put the exact same test into akka-streams-json (which is set to Akka 2.6.20 where you report that it worked) and its behaving the same way as Pekko.

@gchudnov I have a sneaking suspicion that there wasn't any behaviour change (I guess if there was it would have already been reported one way or another) but rather there were at some points in time really slow chunked responses which general. I can reproduce `head of empty stream` but not the source never completing/finishing even though I am doing `Source.fromIterator(() => s.grouped(1)` which means every single character is in its own chunk

**Comment by gchudnov** [comment]
@mdedetrich 
Thank you for trying to reproduce it, I'll check soon

**Comment by gchudnov** [comment]
hm.. indeed something tricky, trying to restore the code that was producing an error and reproduce.

**Comment by mdedetrich** [comment]
Closing due to https://github.com/mdedetrich/pekko-streams-circe/pull/93

**Pull request closed without merging**
